<?php
Class AbstractLogger extends AbstractLoggerCore {}
Class Address extends AddressCore {}
Class AddressController extends AddressControllerCore {}
Class AddressFormat extends AddressFormatCore {}
Class AddressesController extends AddressesControllerCore {}
Class AdminAccessController extends AdminAccessControllerCore {}
Class AdminAddonsCatalogController extends AdminAddonsCatalogControllerCore {}
Class AdminAddressesController extends AdminAddressesControllerCore {}
Class AdminAdminPreferencesController extends AdminAdminPreferencesControllerCore {}
Class AdminAttachmentsController extends AdminAttachmentsControllerCore {}
Class AdminAttributeGeneratorController extends AdminAttributeGeneratorControllerCore {}
Class AdminAttributesGroupsController extends AdminAttributesGroupsControllerCore {}
Class AdminBackupController extends AdminBackupControllerCore {}
Class AdminCarrierWizardController extends AdminCarrierWizardControllerCore {}
Class AdminCarriersController extends AdminCarriersControllerCore {}
Class AdminCartRulesController extends AdminCartRulesControllerCore {}
Class AdminCartsController extends AdminCartsControllerCore {}
Class AdminCategoriesController extends AdminCategoriesControllerCore {}
Class AdminCmsCategoriesController extends AdminCmsCategoriesControllerCore {}
Class AdminCmsContentController extends AdminCmsContentControllerCore {}
Class AdminCmsController extends AdminCmsControllerCore {}
Class AdminContactsController extends AdminContactsControllerCore {}
Class AdminController extends AdminControllerCore {}
Class AdminCountriesController extends AdminCountriesControllerCore {}
Class AdminCurrenciesController extends AdminCurrenciesControllerCore {}
Class AdminCustomerPreferencesController extends AdminCustomerPreferencesControllerCore {}
Class AdminCustomerThreadsController extends AdminCustomerThreadsControllerCore {}
Class AdminCustomersController extends AdminCustomersControllerCore {}
Class AdminDashboardController extends AdminDashboardControllerCore {}
Class AdminDeliverySlipController extends AdminDeliverySlipControllerCore {}
Class AdminEmailsController extends AdminEmailsControllerCore {}
Class AdminEmployeesController extends AdminEmployeesControllerCore {}
Class AdminFeaturesController extends AdminFeaturesControllerCore {}
Class AdminGendersController extends AdminGendersControllerCore {}
Class AdminGeolocationController extends AdminGeolocationControllerCore {}
Class AdminGroupsController extends AdminGroupsControllerCore {}
Class AdminImagesController extends AdminImagesControllerCore {}
Class AdminImportController extends AdminImportControllerCore {}
Class AdminInformationController extends AdminInformationControllerCore {}
Class AdminInvoicesController extends AdminInvoicesControllerCore {}
Class AdminLanguagesController extends AdminLanguagesControllerCore {}
Class AdminLocalizationController extends AdminLocalizationControllerCore {}
Class AdminLoginController extends AdminLoginControllerCore {}
Class AdminLogsController extends AdminLogsControllerCore {}
Class AdminMaintenanceController extends AdminMaintenanceControllerCore {}
Class AdminManufacturersController extends AdminManufacturersControllerCore {}
Class AdminMarketingController extends AdminMarketingControllerCore {}
Class AdminMetaController extends AdminMetaControllerCore {}
Class AdminModulesController extends AdminModulesControllerCore {}
Class AdminModulesPositionsController extends AdminModulesPositionsControllerCore {}
Class AdminNotFoundController extends AdminNotFoundControllerCore {}
Class AdminOrderMessageController extends AdminOrderMessageControllerCore {}
Class AdminOrderPreferencesController extends AdminOrderPreferencesControllerCore {}
Class AdminOrdersController extends AdminOrdersControllerCore {}
Class AdminOutstandingController extends AdminOutstandingControllerCore {}
Class AdminPPreferencesController extends AdminPPreferencesControllerCore {}
Class AdminPatternsController extends AdminPatternsControllerCore {}
Class AdminPaymentController extends AdminPaymentControllerCore {}
Class AdminPdfController extends AdminPdfControllerCore {}
Class AdminPerformanceController extends AdminPerformanceControllerCore {}
Class AdminPreferencesController extends AdminPreferencesControllerCore {}
Class AdminProductsController extends AdminProductsControllerCore {}
Class AdminProfilesController extends AdminProfilesControllerCore {}
Class AdminQuickAccessesController extends AdminQuickAccessesControllerCore {}
Class AdminRangePriceController extends AdminRangePriceControllerCore {}
Class AdminRangeWeightController extends AdminRangeWeightControllerCore {}
Class AdminReferrersController extends AdminReferrersControllerCore {}
Class AdminRequestSqlController extends AdminRequestSqlControllerCore {}
Class AdminReturnController extends AdminReturnControllerCore {}
Class AdminScenesController extends AdminScenesControllerCore {}
Class AdminSearchConfController extends AdminSearchConfControllerCore {}
Class AdminSearchController extends AdminSearchControllerCore {}
Class AdminSearchEnginesController extends AdminSearchEnginesControllerCore {}
Class AdminShippingController extends AdminShippingControllerCore {}
Class AdminShopController extends AdminShopControllerCore {}
Class AdminShopGroupController extends AdminShopGroupControllerCore {}
Class AdminShopUrlController extends AdminShopUrlControllerCore {}
Class AdminSlipController extends AdminSlipControllerCore {}
Class AdminSpecificPriceRuleController extends AdminSpecificPriceRuleControllerCore {}
Class AdminStatesController extends AdminStatesControllerCore {}
Class AdminStatsController extends AdminStatsControllerCore {}
Class AdminStatsTabController extends AdminStatsTabControllerCore {}
Class AdminStatusesController extends AdminStatusesControllerCore {}
Class AdminStockConfigurationController extends AdminStockConfigurationControllerCore {}
Class AdminStockCoverController extends AdminStockCoverControllerCore {}
Class AdminStockInstantStateController extends AdminStockInstantStateControllerCore {}
Class AdminStockManagementController extends AdminStockManagementControllerCore {}
Class AdminStockMvtController extends AdminStockMvtControllerCore {}
Class AdminStoresController extends AdminStoresControllerCore {}
Class AdminSuppliersController extends AdminSuppliersControllerCore {}
Class AdminSupplyOrdersController extends AdminSupplyOrdersControllerCore {}
Class AdminTab extends AdminTabCore {}
Class AdminTabsController extends AdminTabsControllerCore {}
Class AdminTagsController extends AdminTagsControllerCore {}
Class AdminTaxRulesGroupController extends AdminTaxRulesGroupControllerCore {}
Class AdminTaxesController extends AdminTaxesControllerCore {}
Class AdminThemesController extends AdminThemesControllerCore {}
Class AdminTrackingController extends AdminTrackingControllerCore {}
Class AdminTranslationsController extends AdminTranslationsControllerCore {}
Class AdminWarehousesController extends AdminWarehousesControllerCore {}
Class AdminWebserviceController extends AdminWebserviceControllerCore {}
Class AdminZonesController extends AdminZonesControllerCore {}
Class Alias extends AliasCore {}
Class Attachment extends AttachmentCore {}
Class AttachmentController extends AttachmentControllerCore {}
Class Attribute extends AttributeCore {}
Class AttributeGroup extends AttributeGroupCore {}
Class AuthController extends AuthControllerCore {}
Class BestSalesController extends BestSalesControllerCore {}
Class Blowfish extends BlowfishCore {}
Class CMS extends CMSCore {}
Class CMSCategory extends CMSCategoryCore {}
Class CSV extends CSVCore {}
Class Cache extends CacheCore {}
Class CacheApc extends CacheApcCore {}
Class CacheFs extends CacheFsCore {}
Class CacheMemcache extends CacheMemcacheCore {}
Class CacheXcache extends CacheXcacheCore {}
Class Carrier extends CarrierCore {}
Class CarrierModule extends CarrierModuleCore {}
Class Cart extends CartCore {}
Class CartController extends CartControllerCore {}
Class CartRule extends CartRuleCore {}
Class Category extends CategoryCore {}
Class CategoryController extends CategoryControllerCore {}
Class ChangeCurrencyController extends ChangeCurrencyControllerCore {}
Class Chart extends ChartCore {}
Class CmsController extends CmsControllerCore {}
Class Combination extends CombinationCore {}
Class CompareController extends CompareControllerCore {}
Class CompareProduct extends CompareProductCore {}
Class Configuration extends ConfigurationCore {}
Class ConfigurationKPI extends ConfigurationKPICore {}
Class ConfigurationTest extends ConfigurationTestCore {}
Class Connection extends ConnectionCore {}
Class ConnectionsSource extends ConnectionsSourceCore {}
Class Contact extends ContactCore {}
Class ContactController extends ContactControllerCore {}
Class Context extends ContextCore {}
Class Controller extends ControllerCore {}
Class ControllerFactory extends ControllerFactoryCore {}
Class Cookie extends CookieCore {}
Class Country extends CountryCore {}
Class County extends CountyCore {}
Class Currency extends CurrencyCore {}
Class Customer extends CustomerCore {}
Class CustomerMessage extends CustomerMessageCore {}
Class CustomerThread extends CustomerThreadCore {}
Class Customization extends CustomizationCore {}
Class CustomizationField extends CustomizationFieldCore {}
Class DateRange extends DateRangeCore {}
Class Db extends DbCore {}
Class DbMySQLi extends DbMySQLiCore {}
Class DbPDO extends DbPDOCore {}
Class DbQuery extends DbQueryCore {}
Class Delivery extends DeliveryCore {}
Class Discount extends DiscountCore {}
Class DiscountController extends DiscountControllerCore {}
Class Dispatcher extends DispatcherCore {}
Class Employee extends EmployeeCore {}
Class Feature extends FeatureCore {}
Class FeatureValue extends FeatureValueCore {}
Class FileLogger extends FileLoggerCore {}
Class FileUploader extends FileUploaderCore {}
Class FrontController extends FrontControllerCore {}
Class Gender extends GenderCore {}
Class GetFileController extends GetFileControllerCore {}
Class Group extends GroupCore {}
Class GroupReduction extends GroupReductionCore {}
Class Guest extends GuestCore {}
Class GuestTrackingController extends GuestTrackingControllerCore {}
Class HTMLTemplate extends HTMLTemplateCore {}
Class HTMLTemplateDeliverySlip extends HTMLTemplateDeliverySlipCore {}
Class HTMLTemplateInvoice extends HTMLTemplateInvoiceCore {}
Class HTMLTemplateOrderReturn extends HTMLTemplateOrderReturnCore {}
Class HTMLTemplateOrderSlip extends HTMLTemplateOrderSlipCore {}
Class HTMLTemplateSupplyOrderForm extends HTMLTemplateSupplyOrderFormCore {}
Class Helper extends HelperCore {}
Class HelperCalendar extends HelperCalendarCore {}
Class HelperForm extends HelperFormCore {}
Class HelperImageUploader extends HelperImageUploaderCore {}
Class HelperKpi extends HelperKpiCore {}
Class HelperKpiRow extends HelperKpiRowCore {}
Class HelperList extends HelperListCore {}
Class HelperOptions extends HelperOptionsCore {}
Class HelperTreeCategories extends HelperTreeCategoriesCore {}
Class HelperTreeShops extends HelperTreeShopsCore {}
Class HelperUploader extends HelperUploaderCore {}
Class HelperView extends HelperViewCore {}
Class HistoryController extends HistoryControllerCore {}
Class Hook extends HookCore {}
Class ITreeToolbar extends ITreeToolbarCore {}
Class ITreeToolbarButton extends ITreeToolbarButtonCore {}
Class IdentityController extends IdentityControllerCore {}
Class Image extends ImageCore {}
Class ImageManager extends ImageManagerCore {}
Class ImageType extends ImageTypeCore {}
Class ImportModule extends ImportModuleCore {}
Class IndexController extends IndexControllerCore {}
Class Language extends LanguageCore {}
Class Link extends LinkCore {}
Class LocalizationPack extends LocalizationPackCore {}
Class Mail extends MailCore {}
Class Manufacturer extends ManufacturerCore {}
Class ManufacturerController extends ManufacturerControllerCore {}
Class Media extends MediaCore {}
Class Message extends MessageCore {}
Class Meta extends MetaCore {}
Class Module extends ModuleCore {}
Class ModuleAdminController extends ModuleAdminControllerCore {}
Class ModuleFrontController extends ModuleFrontControllerCore {}
Class ModuleGraph extends ModuleGraphCore {}
Class ModuleGraphEngine extends ModuleGraphEngineCore {}
Class ModuleGrid extends ModuleGridCore {}
Class ModuleGridEngine extends ModuleGridEngineCore {}
Class MyAccountController extends MyAccountControllerCore {}
Class MySQL extends MySQLCore {}
Class NewProductsController extends NewProductsControllerCore {}
Class Notification extends NotificationCore {}
Class ObjectModel extends ObjectModelCore {}
Class Order extends OrderCore {}
Class OrderCarrier extends OrderCarrierCore {}
Class OrderCartRule extends OrderCartRuleCore {}
Class OrderConfirmationController extends OrderConfirmationControllerCore {}
Class OrderController extends OrderControllerCore {}
Class OrderDetail extends OrderDetailCore {}
Class OrderDetailController extends OrderDetailControllerCore {}
Class OrderDiscount extends OrderDiscountCore {}
Class OrderFollowController extends OrderFollowControllerCore {}
Class OrderHistory extends OrderHistoryCore {}
Class OrderInvoice extends OrderInvoiceCore {}
Class OrderMessage extends OrderMessageCore {}
Class OrderOpcController extends OrderOpcControllerCore {}
Class OrderPayment extends OrderPaymentCore {}
Class OrderReturn extends OrderReturnCore {}
Class OrderReturnController extends OrderReturnControllerCore {}
Class OrderReturnState extends OrderReturnStateCore {}
Class OrderSlip extends OrderSlipCore {}
Class OrderSlipController extends OrderSlipControllerCore {}
Class OrderState extends OrderStateCore {}
Class PDF extends PDFCore {}
Class PDFGenerator extends PDFGeneratorCore {}
Class Pack extends PackCore {}
Class Page extends PageCore {}
Class PageNotFoundController extends PageNotFoundControllerCore {}
Class ParentOrderController extends ParentOrderControllerCore {}
Class PasswordController extends PasswordControllerCore {}
Class PaymentCC extends PaymentCCCore {}
Class PaymentModule extends PaymentModuleCore {}
Class PdfInvoiceController extends PdfInvoiceControllerCore {}
Class PdfOrderReturnController extends PdfOrderReturnControllerCore {}
Class PdfOrderSlipController extends PdfOrderSlipControllerCore {}
Class PrestaShopBackup extends PrestaShopBackupCore {}
Class PrestaShopCollection extends PrestaShopCollectionCore {}
Class PrestaShopDatabaseException extends PrestaShopDatabaseExceptionCore {}
Class PrestaShopException extends PrestaShopExceptionCore {}
Class PrestaShopLogger extends PrestaShopLoggerCore {}
Class PrestaShopModuleException extends PrestaShopModuleExceptionCore {}
Class PrestaShopPaymentException extends PrestaShopPaymentExceptionCore {}
Class PricesDropController extends PricesDropControllerCore {}
Class Product extends ProductCore {}
Class ProductController extends ProductControllerCore {}
Class ProductDownload extends ProductDownloadCore {}
Class ProductSale extends ProductSaleCore {}
Class ProductSupplier extends ProductSupplierCore {}
Class Profile extends ProfileCore {}
Class QuickAccess extends QuickAccessCore {}
Class RangePrice extends RangePriceCore {}
Class RangeWeight extends RangeWeightCore {}
Class Referrer extends ReferrerCore {}
Class RequestSql extends RequestSqlCore {}
Class Rijndael extends RijndaelCore {}
Class Risk extends RiskCore {}
Class Scene extends SceneCore {}
Class Search extends SearchCore {}
Class SearchController extends SearchControllerCore {}
Class SearchEngine extends SearchEngineCore {}
Class Shop extends ShopCore {}
Class ShopGroup extends ShopGroupCore {}
Class ShopUrl extends ShopUrlCore {}
Class SitemapController extends SitemapControllerCore {}
Class SpecificPrice extends SpecificPriceCore {}
Class SpecificPriceRule extends SpecificPriceRuleCore {}
Class State extends StateCore {}
Class StatisticsController extends StatisticsControllerCore {}
Class Stock extends StockCore {}
Class StockAvailable extends StockAvailableCore {}
Class StockManager extends StockManagerCore {}
Class StockManagerFactory extends StockManagerFactoryCore {}
Class StockManagerModule extends StockManagerModuleCore {}
Class StockMvt extends StockMvtCore {}
Class StockMvtReason extends StockMvtReasonCore {}
Class StockMvtWS extends StockMvtWSCore {}
Class Store extends StoreCore {}
Class StoresController extends StoresControllerCore {}
Class Supplier extends SupplierCore {}
Class SupplierController extends SupplierControllerCore {}
Class SupplyOrder extends SupplyOrderCore {}
Class SupplyOrderDetail extends SupplyOrderDetailCore {}
Class SupplyOrderHistory extends SupplyOrderHistoryCore {}
Class SupplyOrderReceiptHistory extends SupplyOrderReceiptHistoryCore {}
Class SupplyOrderState extends SupplyOrderStateCore {}
Class Tab extends TabCore {}
Class Tag extends TagCore {}
Class Tax extends TaxCore {}
Class TaxCalculator extends TaxCalculatorCore {}
Class TaxManagerFactory extends TaxManagerFactoryCore {}
Class TaxManagerModule extends TaxManagerModuleCore {}
Class TaxRule extends TaxRuleCore {}
Class TaxRulesGroup extends TaxRulesGroupCore {}
Class TaxRulesTaxManager extends TaxRulesTaxManagerCore {}
Class Theme extends ThemeCore {}
Class Tools extends ToolsCore {}
Class Translate extends TranslateCore {}
Class TranslatedConfiguration extends TranslatedConfigurationCore {}
Class Tree extends TreeCore {}
Class TreeToolbar extends TreeToolbarCore {}
Class TreeToolbarButton extends TreeToolbarButtonCore {}
Class TreeToolbarLink extends TreeToolbarLinkCore {}
Class TreeToolbarSearch extends TreeToolbarSearchCore {}
Class TreeToolbarSearchCategories extends TreeToolbarSearchCategoriesCore {}
Class Upgrader extends UpgraderCore {}
Class Uploader extends UploaderCore {}
Class Validate extends ValidateCore {}
Class Warehouse extends WarehouseCore {}
Class WarehouseProductLocation extends WarehouseProductLocationCore {}
Class WebserviceException extends WebserviceExceptionCore {}
Class WebserviceKey extends WebserviceKeyCore {}
Class WebserviceOutputBuilder extends WebserviceOutputBuilderCore {}
Class WebserviceOutputXML extends WebserviceOutputXMLCore {}
Class WebserviceRequest extends WebserviceRequestCore {}
Class WebserviceSpecificManagementImages extends WebserviceSpecificManagementImagesCore {}
Class WebserviceSpecificManagementSearch extends WebserviceSpecificManagementSearchCore {}
Class Zone extends ZoneCore {}
