<?php
class AbstractLogger extends AbstractLoggerCore {}
class Address extends AddressCore {}
class AddressController extends AddressControllerCore {}
class AddressFormat extends AddressFormatCore {}
class AddressesController extends AddressesControllerCore {}
class AdminAccessController extends AdminAccessControllerCore {}
class AdminAddonsCatalogController extends AdminAddonsCatalogControllerCore {}
class AdminAddressesController extends AdminAddressesControllerCore {}
class AdminAdminPreferencesController extends AdminAdminPreferencesControllerCore {}
class AdminAttachmentsController extends AdminAttachmentsControllerCore {}
class AdminAttributeGeneratorController extends AdminAttributeGeneratorControllerCore {}
class AdminAttributesGroupsController extends AdminAttributesGroupsControllerCore {}
class AdminBackupController extends AdminBackupControllerCore {}
class AdminCarrierWizardController extends AdminCarrierWizardControllerCore {}
class AdminCarriersController extends AdminCarriersControllerCore {}
class AdminCartRulesController extends AdminCartRulesControllerCore {}
class AdminCartsController extends AdminCartsControllerCore {}
class AdminCategoriesController extends AdminCategoriesControllerCore {}
class AdminCmsCategoriesController extends AdminCmsCategoriesControllerCore {}
class AdminCmsContentController extends AdminCmsContentControllerCore {}
class AdminCmsController extends AdminCmsControllerCore {}
class AdminContactsController extends AdminContactsControllerCore {}
class AdminController extends AdminControllerCore {}
class AdminCountriesController extends AdminCountriesControllerCore {}
class AdminCurrenciesController extends AdminCurrenciesControllerCore {}
class AdminCustomerPreferencesController extends AdminCustomerPreferencesControllerCore {}
class AdminCustomerThreadsController extends AdminCustomerThreadsControllerCore {}
class AdminCustomersController extends AdminCustomersControllerCore {}
class AdminDashboardController extends AdminDashboardControllerCore {}
class AdminDeliverySlipController extends AdminDeliverySlipControllerCore {}
class AdminEmailsController extends AdminEmailsControllerCore {}
class AdminEmployeesController extends AdminEmployeesControllerCore {}
class AdminFeaturesController extends AdminFeaturesControllerCore {}
class AdminGendersController extends AdminGendersControllerCore {}
class AdminGeolocationController extends AdminGeolocationControllerCore {}
class AdminGroupsController extends AdminGroupsControllerCore {}
class AdminImagesController extends AdminImagesControllerCore {}
class AdminImportController extends AdminImportControllerCore {}
class AdminInformationController extends AdminInformationControllerCore {}
class AdminInvoicesController extends AdminInvoicesControllerCore {}
class AdminLanguagesController extends AdminLanguagesControllerCore {}
class AdminLocalizationController extends AdminLocalizationControllerCore {}
class AdminLoginController extends AdminLoginControllerCore {}
class AdminLogsController extends AdminLogsControllerCore {}
class AdminMaintenanceController extends AdminMaintenanceControllerCore {}
class AdminManufacturersController extends AdminManufacturersControllerCore {}
class AdminMarketingController extends AdminMarketingControllerCore {}
class AdminMetaController extends AdminMetaControllerCore {}
class AdminModulesController extends AdminModulesControllerCore {}
class AdminModulesPositionsController extends AdminModulesPositionsControllerCore {}
class AdminNotFoundController extends AdminNotFoundControllerCore {}
class AdminOrderMessageController extends AdminOrderMessageControllerCore {}
class AdminOrderPreferencesController extends AdminOrderPreferencesControllerCore {}
class AdminOrdersController extends AdminOrdersControllerCore {}
class AdminOutstandingController extends AdminOutstandingControllerCore {}
class AdminPPreferencesController extends AdminPPreferencesControllerCore {}
class AdminPatternsController extends AdminPatternsControllerCore {}
class AdminPaymentController extends AdminPaymentControllerCore {}
class AdminPdfController extends AdminPdfControllerCore {}
class AdminPerformanceController extends AdminPerformanceControllerCore {}
class AdminPreferencesController extends AdminPreferencesControllerCore {}
class AdminProductsController extends AdminProductsControllerCore {}
class AdminProfilesController extends AdminProfilesControllerCore {}
class AdminQuickAccessesController extends AdminQuickAccessesControllerCore {}
class AdminRangePriceController extends AdminRangePriceControllerCore {}
class AdminRangeWeightController extends AdminRangeWeightControllerCore {}
class AdminReferrersController extends AdminReferrersControllerCore {}
class AdminRequestSqlController extends AdminRequestSqlControllerCore {}
class AdminReturnController extends AdminReturnControllerCore {}
class AdminScenesController extends AdminScenesControllerCore {}
class AdminSearchConfController extends AdminSearchConfControllerCore {}
class AdminSearchController extends AdminSearchControllerCore {}
class AdminSearchEnginesController extends AdminSearchEnginesControllerCore {}
class AdminShippingController extends AdminShippingControllerCore {}
class AdminShopController extends AdminShopControllerCore {}
class AdminShopGroupController extends AdminShopGroupControllerCore {}
class AdminShopUrlController extends AdminShopUrlControllerCore {}
class AdminSlipController extends AdminSlipControllerCore {}
class AdminSpecificPriceRuleController extends AdminSpecificPriceRuleControllerCore {}
class AdminStatesController extends AdminStatesControllerCore {}
class AdminStatsController extends AdminStatsControllerCore {}
class AdminStatsTabController extends AdminStatsTabControllerCore {}
class AdminStatusesController extends AdminStatusesControllerCore {}
class AdminStockConfigurationController extends AdminStockConfigurationControllerCore {}
class AdminStockCoverController extends AdminStockCoverControllerCore {}
class AdminStockInstantStateController extends AdminStockInstantStateControllerCore {}
class AdminStockManagementController extends AdminStockManagementControllerCore {}
class AdminStockMvtController extends AdminStockMvtControllerCore {}
class AdminStoresController extends AdminStoresControllerCore {}
class AdminSuppliersController extends AdminSuppliersControllerCore {}
class AdminSupplyOrdersController extends AdminSupplyOrdersControllerCore {}
class AdminTab extends AdminTabCore {}
class AdminTabsController extends AdminTabsControllerCore {}
class AdminTagsController extends AdminTagsControllerCore {}
class AdminTaxRulesGroupController extends AdminTaxRulesGroupControllerCore {}
class AdminTaxesController extends AdminTaxesControllerCore {}
class AdminThemesController extends AdminThemesControllerCore {}
class AdminTrackingController extends AdminTrackingControllerCore {}
class AdminTranslationsController extends AdminTranslationsControllerCore {}
class AdminWarehousesController extends AdminWarehousesControllerCore {}
class AdminWebserviceController extends AdminWebserviceControllerCore {}
class AdminZonesController extends AdminZonesControllerCore {}
class Alias extends AliasCore {}
class Attachment extends AttachmentCore {}
class AttachmentController extends AttachmentControllerCore {}
class Attribute extends AttributeCore {}
class AttributeGroup extends AttributeGroupCore {}
class AuthController extends AuthControllerCore {}
class BestSalesController extends BestSalesControllerCore {}
class Blowfish extends BlowfishCore {}
class CMS extends CMSCore {}
class CMSCategory extends CMSCategoryCore {}
class CSV extends CSVCore {}
class Cache extends CacheCore {}
class CacheApc extends CacheApcCore {}
class CacheFs extends CacheFsCore {}
class CacheMemcache extends CacheMemcacheCore {}
class CacheXcache extends CacheXcacheCore {}
class Carrier extends CarrierCore {}
class CarrierModule extends CarrierModuleCore {}
class Cart extends CartCore {}
class CartController extends CartControllerCore {}
class CartRule extends CartRuleCore {}
class Category extends CategoryCore {}
class CategoryController extends CategoryControllerCore {}
class ChangeCurrencyController extends ChangeCurrencyControllerCore {}
class Chart extends ChartCore {}
class CmsController extends CmsControllerCore {}
class Combination extends CombinationCore {}
class CompareController extends CompareControllerCore {}
class CompareProduct extends CompareProductCore {}
class Configuration extends ConfigurationCore {}
class ConfigurationKPI extends ConfigurationKPICore {}
class ConfigurationTest extends ConfigurationTestCore {}
class Connection extends ConnectionCore {}
class ConnectionsSource extends ConnectionsSourceCore {}
class Contact extends ContactCore {}
class ContactController extends ContactControllerCore {}
class Context extends ContextCore {}
class Controller extends ControllerCore {}
class ControllerFactory extends ControllerFactoryCore {}
class Cookie extends CookieCore {}
class Country extends CountryCore {}
class County extends CountyCore {}
class Currency extends CurrencyCore {}
class Customer extends CustomerCore {}
class CustomerMessage extends CustomerMessageCore {}
class CustomerThread extends CustomerThreadCore {}
class Customization extends CustomizationCore {}
class CustomizationField extends CustomizationFieldCore {}
class DateRange extends DateRangeCore {}
class Db extends DbCore {}
class DbMySQLi extends DbMySQLiCore {}
class DbPDO extends DbPDOCore {}
class DbQuery extends DbQueryCore {}
class Delivery extends DeliveryCore {}
class Discount extends DiscountCore {}
class DiscountController extends DiscountControllerCore {}
class Dispatcher extends DispatcherCore {}
class Employee extends EmployeeCore {}
class Feature extends FeatureCore {}
class FeatureValue extends FeatureValueCore {}
class FileLogger extends FileLoggerCore {}
class FileUploader extends FileUploaderCore {}
class FrontController extends FrontControllerCore {}
class Gender extends GenderCore {}
class GetFileController extends GetFileControllerCore {}
class Group extends GroupCore {}
class GroupReduction extends GroupReductionCore {}
class Guest extends GuestCore {}
class GuestTrackingController extends GuestTrackingControllerCore {}
class HTMLTemplate extends HTMLTemplateCore {}
class HTMLTemplateDeliverySlip extends HTMLTemplateDeliverySlipCore {}
class HTMLTemplateInvoice extends HTMLTemplateInvoiceCore {}
class HTMLTemplateOrderReturn extends HTMLTemplateOrderReturnCore {}
class HTMLTemplateOrderSlip extends HTMLTemplateOrderSlipCore {}
class HTMLTemplateSupplyOrderForm extends HTMLTemplateSupplyOrderFormCore {}
class Helper extends HelperCore {}
class HelperCalendar extends HelperCalendarCore {}
class HelperForm extends HelperFormCore {}
class HelperImageUploader extends HelperImageUploaderCore {}
class HelperKpi extends HelperKpiCore {}
class HelperKpiRow extends HelperKpiRowCore {}
class HelperList extends HelperListCore {}
class HelperOptions extends HelperOptionsCore {}
class HelperTreeCategories extends HelperTreeCategoriesCore {}
class HelperTreeShops extends HelperTreeShopsCore {}
class HelperUploader extends HelperUploaderCore {}
class HelperView extends HelperViewCore {}
class HistoryController extends HistoryControllerCore {}
class Hook extends HookCore {}
class ITreeToolbar extends ITreeToolbarCore {}
class ITreeToolbarButton extends ITreeToolbarButtonCore {}
class IdentityController extends IdentityControllerCore {}
class Image extends ImageCore {}
class ImageManager extends ImageManagerCore {}
class ImageType extends ImageTypeCore {}
class ImportModule extends ImportModuleCore {}
class IndexController extends IndexControllerCore {}
class Language extends LanguageCore {}
class Link extends LinkCore {}
class LocalizationPack extends LocalizationPackCore {}
class Mail extends MailCore {}
class Manufacturer extends ManufacturerCore {}
class ManufacturerController extends ManufacturerControllerCore {}
class Media extends MediaCore {}
class Message extends MessageCore {}
class Meta extends MetaCore {}
class Module extends ModuleCore {}
class ModuleAdminController extends ModuleAdminControllerCore {}
class ModuleFrontController extends ModuleFrontControllerCore {}
class ModuleGraph extends ModuleGraphCore {}
class ModuleGraphEngine extends ModuleGraphEngineCore {}
class ModuleGrid extends ModuleGridCore {}
class ModuleGridEngine extends ModuleGridEngineCore {}
class MyAccountController extends MyAccountControllerCore {}
class MySQL extends MySQLCore {}
class NewProductsController extends NewProductsControllerCore {}
class Notification extends NotificationCore {}
class ObjectModel extends ObjectModelCore {}
class Order extends OrderCore {}
class OrderCarrier extends OrderCarrierCore {}
class OrderCartRule extends OrderCartRuleCore {}
class OrderConfirmationController extends OrderConfirmationControllerCore {}
class OrderController extends OrderControllerCore {}
class OrderDetail extends OrderDetailCore {}
class OrderDetailController extends OrderDetailControllerCore {}
class OrderDiscount extends OrderDiscountCore {}
class OrderFollowController extends OrderFollowControllerCore {}
class OrderHistory extends OrderHistoryCore {}
class OrderInvoice extends OrderInvoiceCore {}
class OrderMessage extends OrderMessageCore {}
class OrderOpcController extends OrderOpcControllerCore {}
class OrderPayment extends OrderPaymentCore {}
class OrderReturn extends OrderReturnCore {}
class OrderReturnController extends OrderReturnControllerCore {}
class OrderReturnState extends OrderReturnStateCore {}
class OrderSlip extends OrderSlipCore {}
class OrderSlipController extends OrderSlipControllerCore {}
class OrderState extends OrderStateCore {}
class PDF extends PDFCore {}
class PDFGenerator extends PDFGeneratorCore {}
class Pack extends PackCore {}
class Page extends PageCore {}
class PageNotFoundController extends PageNotFoundControllerCore {}
class ParentOrderController extends ParentOrderControllerCore {}
class PasswordController extends PasswordControllerCore {}
class PaymentCC extends PaymentCCCore {}
class PaymentModule extends PaymentModuleCore {}
class PdfInvoiceController extends PdfInvoiceControllerCore {}
class PdfOrderReturnController extends PdfOrderReturnControllerCore {}
class PdfOrderSlipController extends PdfOrderSlipControllerCore {}
class PrestaShopBackup extends PrestaShopBackupCore {}
class PrestaShopCollection extends PrestaShopCollectionCore {}
class PrestaShopDatabaseException extends PrestaShopDatabaseExceptionCore {}
class PrestaShopException extends PrestaShopExceptionCore {}
class PrestaShopLogger extends PrestaShopLoggerCore {}
class PrestaShopModuleException extends PrestaShopModuleExceptionCore {}
class PrestaShopPaymentException extends PrestaShopPaymentExceptionCore {}
class PricesDropController extends PricesDropControllerCore {}
class Product extends ProductCore {}
class ProductController extends ProductControllerCore {}
class ProductDownload extends ProductDownloadCore {}
class ProductSale extends ProductSaleCore {}
class ProductSupplier extends ProductSupplierCore {}
class Profile extends ProfileCore {}
class QuickAccess extends QuickAccessCore {}
class RangePrice extends RangePriceCore {}
class RangeWeight extends RangeWeightCore {}
class Referrer extends ReferrerCore {}
class RequestSql extends RequestSqlCore {}
class Rijndael extends RijndaelCore {}
class Risk extends RiskCore {}
class Scene extends SceneCore {}
class Search extends SearchCore {}
class SearchController extends SearchControllerCore {}
class SearchEngine extends SearchEngineCore {}
class Shop extends ShopCore {}
class ShopGroup extends ShopGroupCore {}
class ShopUrl extends ShopUrlCore {}
class SitemapController extends SitemapControllerCore {}
class SpecificPrice extends SpecificPriceCore {}
class SpecificPriceRule extends SpecificPriceRuleCore {}
class State extends StateCore {}
class StatisticsController extends StatisticsControllerCore {}
class Stock extends StockCore {}
class StockAvailable extends StockAvailableCore {}
class StockManager extends StockManagerCore {}
class StockManagerFactory extends StockManagerFactoryCore {}
class StockManagerModule extends StockManagerModuleCore {}
class StockMvt extends StockMvtCore {}
class StockMvtReason extends StockMvtReasonCore {}
class StockMvtWS extends StockMvtWSCore {}
class Store extends StoreCore {}
class StoresController extends StoresControllerCore {}
class Supplier extends SupplierCore {}
class SupplierController extends SupplierControllerCore {}
class SupplyOrder extends SupplyOrderCore {}
class SupplyOrderDetail extends SupplyOrderDetailCore {}
class SupplyOrderHistory extends SupplyOrderHistoryCore {}
class SupplyOrderReceiptHistory extends SupplyOrderReceiptHistoryCore {}
class SupplyOrderState extends SupplyOrderStateCore {}
class Tab extends TabCore {}
class Tag extends TagCore {}
class Tax extends TaxCore {}
class TaxCalculator extends TaxCalculatorCore {}
class TaxManagerFactory extends TaxManagerFactoryCore {}
class TaxManagerModule extends TaxManagerModuleCore {}
class TaxRule extends TaxRuleCore {}
class TaxRulesGroup extends TaxRulesGroupCore {}
class TaxRulesTaxManager extends TaxRulesTaxManagerCore {}
class Theme extends ThemeCore {}
class Tools extends ToolsCore {}
class Translate extends TranslateCore {}
class TranslatedConfiguration extends TranslatedConfigurationCore {}
class Tree extends TreeCore {}
class TreeToolbar extends TreeToolbarCore {}
class TreeToolbarButton extends TreeToolbarButtonCore {}
class TreeToolbarLink extends TreeToolbarLinkCore {}
class TreeToolbarSearch extends TreeToolbarSearchCore {}
class TreeToolbarSearchCategories extends TreeToolbarSearchCategoriesCore {}
class Upgrader extends UpgraderCore {}
class Uploader extends UploaderCore {}
class Validate extends ValidateCore {}
class Warehouse extends WarehouseCore {}
class WarehouseProductLocation extends WarehouseProductLocationCore {}
class WebserviceException extends WebserviceExceptionCore {}
class WebserviceKey extends WebserviceKeyCore {}
class WebserviceOutputBuilder extends WebserviceOutputBuilderCore {}
class WebserviceOutputXML extends WebserviceOutputXMLCore {}
class WebserviceRequest extends WebserviceRequestCore {}
class WebserviceSpecificManagementImages extends WebserviceSpecificManagementImagesCore {}
class WebserviceSpecificManagementSearch extends WebserviceSpecificManagementSearchCore {}
class Zone extends ZoneCore {}
